name: CI

on:
  push:
    branches: [master]
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
  pull_request:
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  test:
    name: Test parser
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-versions: 24
          cache: npm
          cache-dependency-path: package*.json
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@v2
      - name: Test all apart from Node
        uses: tree-sitter/parser-test-action@v2
        with:
          test-python: true
          test-rust: true
      - name: Build Node package
        shell: sh
        run: npm install
        env:
          CXXFLAGS: "-std=c++20"
      - name: Test Node
        shell: sh
        run: node --test bindings/node/*_test.js
