name: Publish Package (NPM)

on:
  workflow_call:
  workflow_dispatch:

env:
  NODE_VERSION: ${{ vars.NODE_VERSION || 24 }}
  TS_ABI_VERSION: ${{ vars.TS_ABI_VERSION || 15 }}
  PACKAGE_NAME: ${{ vars.NPM_PACKAGE_NAME || 'tree-sitter-math' }}

jobs:
  build_wasm:
    name: Build Wasm binaries
    runs-on: ubuntu-24.04
    continue-on-error: true
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: ${{env.NODE_VERSION}}
      - name: Install dependencies
        run: npm i --omit peer --omit optional
        env:
          CXXFLAGS: -std=c++20
      - name: Regenerate parser
        shell: bash
        run: |
          while read -r grammar_dir; do
            pushd "$grammar_dir"
            npm x -- tree-sitter generate
            popd >/dev/null
          done < <(jq -r '.grammars[].path // "."' tree-sitter.json)
        env:
          TREE_SITTER_ABI_VERSION: ${{env.TS_ABI_VERSION}}
      - name: Build Wasm binaries
        run: |
          while read -r grammar_dir; do
            npm x -- tree-sitter build --wasm "$grammar_dir"
          done < <(jq -r '.grammars[].path // "."' tree-sitter.json)
      - name: Upload binaries
        uses: actions/upload-artifact@v6
        with:
          path: "*.wasm"
          name: prebuilds-wasm
          retention-days: 2

  build_node:
    name: Build Node binaries on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - windows-2025
          - windows-11-arm
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-15
          - macos-15-intel
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: ${{env.NODE_VERSION}}
      - name: Install dependencies
        run: npm i --omit peer --omit optional
        env:
          CXXFLAGS: -std=c++20
      - name: Generate parser
        shell: bash
        run: |
          while read -r grammar_dir; do
            pushd "$grammar_dir"
            npm x -- tree-sitter generate
            popd >/dev/null
          done < <(jq -r '.grammars[].path // "."' tree-sitter.json)
        env:
          TREE_SITTER_ABI_VERSION: ${{env.TS_ABI_VERSION}}
      - name: Build binary
        run: npm x -- prebuildify
      - name: Upload binaries
        uses: actions/upload-artifact@v7
        with:
          path: prebuilds/**
          name: prebuilds-${{matrix.os}}
          retention-days: 2

  package:
    name: Publish Node package
    needs: [build_wasm, build_node]
    runs-on: ubuntu-24.04
    environment:
      name: Publishing
      url: https://www.npmjs.com/package/${{env.PACKAGE_NAME}}
    permissions:
      id-token: write
      attestations: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v6
      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          cache: npm
          node-version: ${{env.NODE_VERSION}}
      - name: Download binaries
        uses: actions/download-artifact@v7
        with:
          path: prebuilds
          pattern: prebuilds-*
          merge-multiple: true
      - name: Check binaries
        run: tree prebuilds
      - name: Move Wasm binaries
        continue-on-error: true
        run: mv -v prebuilds/*.wasm .
      - name: Publish to npm
        run: npm publish
