name: Publish Packages

on:
  push:
    tags: ["*"]
    paths:
      - grammar.js
      - src/**
      - test/**
      - bindings/**
      - binding.gyp
  workflow_dispatch:

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  github:
    uses: ./.github/workflows/publish-gh.yml
  npm:
    uses: ./.github/workflows/publish-npm.yml
  crates:
    uses: ./.github/workflows/publish-crates.yml
  pypi:
    uses: ./.github/workflows/publish-pypi.yml
